# Generated by Django 4.0.2 on 2023-09-18 22:15

from django.db import migrations, models
import user_profile.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profilepage_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='birthday',
            field=models.DateField(validators=[user_profile.validators.requires_age_of_18], verbose_name='Birth date'),
        ),
    ]
