# Generated by Django 4.0.2 on 2023-09-30 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_commentsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsection',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='articles.commentsection'),
        ),
    ]
