# Generated by Django 4.0.2 on 2023-10-01 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_commentsection_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsection',
            name='parent_comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='articles.commentsection'),
        ),
    ]
